packages:
  - playground/*
  - packages
catalog:
  typescript: ~5.9.3
  "@typescript/native-preview": 7.0.0-dev.20260212.1
  vite: "npm:rolldown-vite@latest"
  vue-tsc: ^3.2.4
  vue: "beta"
  "@vitejs/plugin-vue": ^6.0.4
